### PR TITLE
Enable t/02_can_run.t to work on Win32 perl installed into a path with spaces in it

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by karenetheridge** [comment]
+1

by the way, "perl in space" means "perl installed into a path with spaces in it".

**Comment by karenetheridge** [comment]
Thanks! Would it be possible to release this soon? Some cpantesters smoker boxes are hung up on this problem.

**Comment by mohawk2** [comment]
Bump. Please release!

**Comment by tokuhirom** [comment]
Sorry, I released it now!

**Comment by mohawk2** [comment]
:+1:

**Pull request merged**
